### ISSUE TITLE
Get access to URI ?

### ISSUE THREAD

**Issue by dorianrod** [domax/cordova-plugin-photos#15]
Hi,
Thanks for this plugin, that's exactly what i was looking for ! 
I've a question about pictures URI: it's very efficient to have a way to create a thumbnail for performance, but it's not really efficient to create a blob for an existing picture (it takes a lot of memory and after a while the app just crash). I there a way to access to picture URI so that i could just use the URI to display the picture inside a <img> ?

**Comment by domax** [comment]
If you have lots of thumbnails and photos to deal with, you have to save them as files in device's storage and use them in your UI as URLs to these files. You may find how to do that in [4th example here](../#examples-3).

**Comment by dorianrod** [comment]
Hi, Thanks for your answer @domax. My problem was to display the user gallery, so if i had to save every thumbnail and pictures, it would lead to a storage issue. I solved my problem with an other plugin (cordova-plugin-photo-library), my use case probably didn't fit so much with this plugin ultimately.
Have a good day
