### ISSUE TITLE
Get native paths of my images

### ISSUE THREAD

**Issue by flogr** [domax/cordova-plugin-photos#16]
Is this possible with this plugin @domax ? I'm not quite shure as i didn't find anything like this...

I'm currently looking for a cordova plugin that lets me read all pictures from a certain gallery on your phone and returns native file urls - so i can share and delete these files from inside my app.

My background: i'm working on a photo-app for Android and iOS that lets you take pictures and places them in specific folders in your gallery. The user has an archive view from inside the app where he should be able to share and delete taken pictures - this only works when i have the native file paths.

I didn't find a cordova photo library plugin that has this feature, the popular "cordova-plugin-photo-library" f.e. isn't able to do so.
Also, hacks like making a tmp copy of the desired image is not an option for me.

**Comment by domax** [comment]
No unfortunately, as far as I know. Both platforms provide just their own native APIs to deal with media data. There are no any "native URLs" - only native objects and descriptors that provide the access to according media data. If there could be "native URLs" there wouldn't be need to create this plugin at all ).
