### ISSUE TITLE
Compilation error on Android

### ISSUE THREAD

**Issue by niconaso** [domax/cordova-plugin-photos#2]
I tried to compile on Androd but it shows me this error:

Error: /Users/niconaso/develop/workspace/project-3-mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/niconaso/develop/workspace/project-3-mobile/platforms/android/src/com/domax/cordova/Photos.java:194: error: try-with-resources is not supported in -source 1.6
		try (final Cursor cursor = query(
		    ^
  (use -source 7 or higher to enable try-with-resources)
/Users/niconaso/develop/workspace/project-3-mobile/platforms/android/src/com/domax/cordova/Photos.java:354: error: diamond operator is not supported in -source 1.6
		final List<T> result = new ArrayList<>();
		                                     ^
  (use -source 7 or higher to enable diamond operator)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by domax** [comment]
Android plugin is written on Java 7, but looks like you're trying to compile it with Java 6.
Just switch your project to Java 7 or 8:
1. Make sure you have installed JDK 7 or 8 (recommended).
2. In your project properties specify source and target compatibility 1.7 or 1.8 (if you use Android Studio, you may find it here: File -> Project Structure -> Modules -> android)

**Comment by domax** [comment]
Or, you may do the same in your project's `build.gradle` script: just replace `JavaVersion.VERSION_1_6` to `JavaVersion.VERSION_1_7`, like that:

``` gradle
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

**Comment by niconaso** [comment]
Thanks!!
I just added this properties

ext.postBuildExtras = {
    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }
    }
}

into build-extras.gradle and put it on platforms/android

**Comment by dnmd** [comment]
Before opening a new issue, I noticed this one, marked as closed. I tried both solutions, via Android studio
`File -> Project Structure -> Modules -> android`

and by adding an `build-extras.gradle` extra file within the

`platforms -> android -> build-extras.gradle`

``` javascript
ext.postBuildExtras = {
    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }
    }
}
```

But in both scenarios an error is throw: [https://i.stack.imgur.com/qBykN.jpg](https://i.stack.imgur.com/qBykN.jpg) Any thoughts @niconaso @domax ?

**Comment by dnmd** [comment]
Okay, it seems that this plugin depends on:

`cordova-plugin-compat`

and somehow didn't get installed after adding this plugin. Adding it fixed the problem.

`cordiva (or ionic) plugin add cordova-plugin-compat --save`

I'll see if I can PR a short note for the `readme`, I think it will help some people out! :)

**Comment by domax** [comment]
@dnmd : I've just added explicit dependency to cordova-plugin-compat

**Comment by piratenmedl** [comment]
Hallo, I'm building with Phonegap Build and have the same error with Android. iOS works well. Does anyone know how to provide Java Version 1.7 in this case? Thanks

**Comment by eddskt** [comment]
> Or, you may do the same in your project's `build.gradle` script: just replace `JavaVersion.VERSION_1_6` to `JavaVersion.VERSION_1_7`, like that:
> 
> ```groovy-gradle
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_7
>         targetCompatibility JavaVersion.VERSION_1_7
>     }
> ```

Thanksssss Solved for me!
